# Generated by Django 5.0.1 on 2024-02-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Recommended', 'Recommended'), ('Best Seller', 'Best Seller')], max_length=100, null=True),
        ),
    ]
