# Generated by Django 5.0.1 on 2024-02-26 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
