# Generated by Django 5.0.1 on 2024-02-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_contact_us_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='product',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
