# Generated by Django 5.0.1 on 2024-02-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_wishlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sub_Category',
            new_name='sub_category',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='sub_Category',
            new_name='sub_category',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
