# Generated by Django 5.0.1 on 2024-02-29 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_sub_category_product_sub_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='name',
        ),
    ]
