# Generated by Django 5.0.1 on 2024-03-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_wishlist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='name',
        ),
    ]
